cc_test(
    name = "Test",
    srcs = ["Test.cc"],
    deps = [
        "//src/Addition:Addition",
        "//src/Subtraction:Subtraction",
        "//src/Division:Division",
        "//src/Multiplication:Multiplication",
        "@com_google_googletest//:gtest",
          "@com_google_googletest//:gtest_main",
    ],
    visibility=["//visibility:public"], 
)